### ISSUE TITLE
Value not saved (multilingual?)

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.formwidget.autocomplete#13]
Possibly related to plone.app.multilingual; at least I only tested it there. Tired of bug hunting now, but let me at least put down some notes.

Setup scenario:
1. Take plone.app.multilingual branch 1.x (Plone 4.3) from github, run its bootstrap and buildout.
2. Create Plone Site, install p.a.multilingual, setup two languages. I pick Dutch and English.
3. Create Dutch page.
4. Create a second page, still in Dutch. (We will pick this page as English translation later, so we would have wanted to create an actual English page in the English language, but there is a problem unrelated to plone.formwidget.autocomplete there.)
5. Return to the first Dutch page
6. Click Actions -> Add Translations.

Now the problem:
A. Use the browse button (contenttree widget) to select the second page, see that a radio button is added in the original form showing the selected page, and submit the form and all is well: the two documents are now related.
B. Instead use the autocomplete input to select the second page, see that a radio button is added in the original form showing the selected page, and submit the form and all is _not_ well: no relation has been added.

I have checked, and the radio button that is added in both these cases is exactly the same, in my case:

```
<input type="radio" checked="checked" name="form.widgets.content" id="form-widgets-content-0" title="None" value="/Plone/nl/soon-to-be-english-page-created-in-dutch-site" class="contenttree-widget required relationchoice-field">
```

So somehow the autocomplete widget does not correctly save the value.

**Comment by jensens** [comment]
still an issue?

**Comment by mauritsvanrees** [comment]
I just now tried it in an old site with old versions and there the problem still exists.
But the customer has not complained. Or maybe they did years ago, but I can't remember.

It probably works fine on master.
I will close this and the related linked issue.
