### ISSUE TITLE
plone.formwidget.autocomplete converts user input to lower case

### ISSUE THREAD

**Issue by bdbaddog** [plone/plone.formwidget.autocomplete#4]
_Original author: do3cc...@googlemail.com (July 06, 2010 14:52:07)_

I am using the autocomplete widget with UserSource, the user I am searching for starts with an uppercase letter and is never found with the autocomplete widget.

_Original issue: http://code.google.com/p/dexterity/issues/detail?id=135_

**Comment by jensens** [comment]
outdated
